use std::fmt::Write as FmtWrite;

use crate::automata::arena::NodeId;
use crate::automata::dfa::Dfa;
use crate::compress::equiv_classes::{compress_dfa, CompressedDfa};
use crate::error::LexError;
use crate::lex_file::parser::LexFile;

use super::traits::CodeEmitter;

/// Emits a POSIX-compliant lex.yy.c file.
pub struct CEmitter {
    /// Whether to suppress the default rule (echo unmatched chars).
    pub suppress_default: bool,
    /// Whether to use equivalence-class compression.
    pub compress: bool,
}

impl CEmitter {
    pub fn new(suppress_default: bool) -> Self {
        Self {
            suppress_default,
            compress: false,
        }
    }

    pub fn with_compression(suppress_default: bool) -> Self {
        Self {
            suppress_default,
            compress: true,
        }
    }

    /// Format the DFA transition table as a C static array.
    fn emit_transition_table(out: &mut String, dfa: &Dfa) {
        let n = dfa.state_count();
        writeln!(out, "static int yy_transition[{}][256] = {{", n).unwrap();
        for i in 0..n {
            let state = dfa.arena.get(NodeId(i));
            write!(out, "  {{").unwrap();
            for (byte_idx, trans) in state.transitions.iter().enumerate() {
                if byte_idx > 0 {
                    write!(out, ",").unwrap();
                }
                match trans {
                    Some(target) => write!(out, "{}", target.0).unwrap(),
                    None => write!(out, "-1").unwrap(),
                }
            }
            if i + 1 < n {
                writeln!(out, "}},").unwrap();
            } else {
                writeln!(out, "}}").unwrap();
            }
        }
        writeln!(out, "}};").unwrap();
    }

    /// Format the DFA accept table.
    fn emit_accept_table(out: &mut String, dfa: &Dfa) {
        let n = dfa.state_count();
        writeln!(out, "static int yy_accept[{}] = {{", n).unwrap();
        write!(out, "  ").unwrap();
        for i in 0..n {
            let state = dfa.arena.get(NodeId(i));
            if i > 0 {
                write!(out, ", ").unwrap();
            }
            match state.accepting {
                // POSIX: rule indices are 1-based in the accept table (0 = non-accepting)
                Some(rule) => write!(out, "{}", rule + 1).unwrap(),
                None => write!(out, "0").unwrap(),
            }
        }
        writeln!(out).unwrap();
        writeln!(out, "}};").unwrap();
    }
    /// Emit the equivalence class mapping table.
    fn emit_ec_table(out: &mut String, cdfa: &CompressedDfa) {
        writeln!(out, "static unsigned char yy_ec[256] = {{").unwrap();
        write!(out, "  ").unwrap();
        for i in 0..256 {
            if i > 0 {
                write!(out, ",").unwrap();
            }
            if i > 0 && i % 16 == 0 {
                write!(out, "\n  ").unwrap();
            }
            write!(out, "{}", cdfa.ec.class_of[i]).unwrap();
        }
        writeln!(out).unwrap();
        writeln!(out, "}};\n").unwrap();
    }

    /// Emit the compressed transition table.
    fn emit_compressed_transition_table(out: &mut String, cdfa: &CompressedDfa) {
        let nc = cdfa.ec.num_classes;
        writeln!(out, "static int yy_transition[{}][{}] = {{", cdfa.num_states, nc).unwrap();
        for s in 0..cdfa.num_states {
            write!(out, "  {{").unwrap();
            for c in 0..nc {
                if c > 0 {
                    write!(out, ",").unwrap();
                }
                write!(out, "{}", cdfa.transitions[s * nc + c]).unwrap();
            }
            if s + 1 < cdfa.num_states {
                writeln!(out, "}},").unwrap();
            } else {
                writeln!(out, "}}").unwrap();
            }
        }
        writeln!(out, "}};\n").unwrap();
    }

    /// Emit the compressed accept table.
    fn emit_compressed_accept_table(out: &mut String, cdfa: &CompressedDfa) {
        writeln!(out, "static int yy_accept[{}] = {{", cdfa.num_states).unwrap();
        write!(out, "  ").unwrap();
        for i in 0..cdfa.num_states {
            if i > 0 {
                write!(out, ", ").unwrap();
            }
            write!(out, "{}", cdfa.accept[i]).unwrap();
        }
        writeln!(out).unwrap();
        writeln!(out, "}};\n").unwrap();
    }}

impl CodeEmitter for CEmitter {
    fn emit(&self, lex_file: &LexFile, dfa: &Dfa) -> Result<String, LexError> {
        let mut out = String::with_capacity(16384);

        // 1. File header
        writeln!(out, "/* Generated by ft_lex */").unwrap();
        writeln!(out, "#include <stdio.h>").unwrap();
        writeln!(out, "#include <string.h>").unwrap();
        writeln!(out, "#include <stdlib.h>").unwrap();
        writeln!(out).unwrap();

        // 2. User header code (from %{{ ... %}})
        if !lex_file.header_code.is_empty() {
            writeln!(out, "/* User header code */").unwrap();
            write!(out, "{}", lex_file.header_code).unwrap();
            writeln!(out).unwrap();
        }

        // 3. DFA tables (compressed or full)
        let cdfa_opt = if self.compress {
            Some(compress_dfa(dfa))
        } else {
            None
        };

        let num_states = dfa.state_count();
        writeln!(out, "#define YY_NUM_STATES {}", num_states).unwrap();
        writeln!(out, "#define YY_START_STATE {}", dfa.start.0).unwrap();
        writeln!(out).unwrap();

        if let Some(ref cdfa) = cdfa_opt {
            Self::emit_ec_table(&mut out, cdfa);
            Self::emit_compressed_transition_table(&mut out, cdfa);
            Self::emit_compressed_accept_table(&mut out, cdfa);
        } else {
            Self::emit_transition_table(&mut out, dfa);
            writeln!(out).unwrap();
            Self::emit_accept_table(&mut out, dfa);
        }
        writeln!(out).unwrap();

        // 4. Globals & buffer
        writeln!(out, "#define YY_BUF_SIZE 16384").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "static char yy_buf[YY_BUF_SIZE + 2];").unwrap();
        writeln!(out, "static int yy_buf_pos = 0;").unwrap();
        writeln!(out, "static int yy_buf_len = 0;").unwrap();
        writeln!(out, "static int yy_at_bol = 1;  /* BOL flag: 1 at start of line */").unwrap();
        writeln!(out, "static int yy_more_flag = 0;").unwrap();
        writeln!(out, "static int yy_more_len = 0;").unwrap();
        writeln!(out, "static char yy_held_char = 0;").unwrap();
        writeln!(out, "static int yy_held_pos = -1;").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "char *yytext = NULL;").unwrap();
        writeln!(out, "int yyleng = 0;").unwrap();
        writeln!(out, "FILE *yyin = NULL;").unwrap();
        writeln!(out, "FILE *yyout = NULL;").unwrap();
        if lex_file.options.yylineno {
            writeln!(out, "int yylineno = 1;").unwrap();
        }
        writeln!(out).unwrap();

        // POSIX macros: ECHO, INITIAL, BEGIN
        writeln!(out, "#define ECHO fwrite(yytext, 1, yyleng, yyout)").unwrap();
        writeln!(out, "#define INITIAL 0").unwrap();
        writeln!(out, "#define BEGIN(sc) ((void)(sc))  /* start conditions stub */").unwrap();
        writeln!(out, "#define YY_START 0").unwrap();
        writeln!(out).unwrap();

        // 5. yywrap declaration (provided by libl or user)
        if !lex_file.options.noyywrap {
            writeln!(out, "extern int yywrap(void);").unwrap();
        } else {
            writeln!(out, "static int yywrap(void) {{ return 1; }}").unwrap();
        }
        writeln!(out).unwrap();

        // POSIX functions: input(), unput(), yymore(), yyless(), yyrestart()
        writeln!(out, "/* POSIX lex functions */").unwrap();
        writeln!(out, "static int yy_refill(void) {{").unwrap();
        writeln!(out, "    /* Shift remaining data to beginning of buffer */").unwrap();
        writeln!(out, "    if (yy_buf_pos > 0 && yy_buf_pos < yy_buf_len) {{").unwrap();
        writeln!(out, "        memmove(yy_buf, yy_buf + yy_buf_pos, yy_buf_len - yy_buf_pos);").unwrap();
        writeln!(out, "        yy_buf_len -= yy_buf_pos;").unwrap();
        writeln!(out, "        yy_buf_pos = 0;").unwrap();
        writeln!(out, "    }} else {{").unwrap();
        writeln!(out, "        yy_buf_pos = 0;").unwrap();
        writeln!(out, "        yy_buf_len = 0;").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "    if (yyin == NULL) yyin = stdin;").unwrap();
        writeln!(out, "    int n = (int)fread(yy_buf + yy_buf_len, 1, YY_BUF_SIZE - yy_buf_len, yyin);").unwrap();
        writeln!(out, "    yy_buf_len += n;").unwrap();
        writeln!(out, "    return n;").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "int input(void) {{").unwrap();
        writeln!(out, "    if (yy_buf_pos >= yy_buf_len) {{").unwrap();
        writeln!(out, "        if (yy_refill() == 0) return EOF;").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "    int c = (unsigned char)yy_buf[yy_buf_pos++];").unwrap();
        writeln!(out, "    if (c == '\\n') yy_at_bol = 1;").unwrap();
        writeln!(out, "    else yy_at_bol = 0;").unwrap();
        writeln!(out, "    return c;").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "void unput(int c) {{").unwrap();
        writeln!(out, "    if (yy_buf_pos > 0) {{").unwrap();
        writeln!(out, "        yy_buf[--yy_buf_pos] = (char)c;").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "void yyrestart(FILE *f) {{").unwrap();
        writeln!(out, "    yyin = f;").unwrap();
        writeln!(out, "    yy_buf_pos = 0;").unwrap();
        writeln!(out, "    yy_buf_len = 0;").unwrap();
        writeln!(out, "    yy_at_bol = 1;").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "void yymore(void) {{").unwrap();
        writeln!(out, "    yy_more_flag = 1;").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "#define yyless(n) do {{ \\").unwrap();
        writeln!(out, "    yy_buf_pos = yy_start_pos + (n); \\").unwrap();
        writeln!(out, "    yyleng = (n); \\").unwrap();
        writeln!(out, "    yytext[yyleng] = yy_save; \\").unwrap();
        writeln!(out, "    yy_save = yytext[yyleng]; \\").unwrap();
        writeln!(out, "    yytext[yyleng] = '\\0'; \\").unwrap();
        writeln!(out, "}} while (0)").unwrap();
        writeln!(out).unwrap();

        // 6. yylex function with proper buffer handling
        writeln!(out, "int yylex(void) {{").unwrap();
        writeln!(out, "    int yy_state;").unwrap();
        writeln!(out, "    int yy_last_accept_state;").unwrap();
        writeln!(out, "    int yy_last_accept_pos;").unwrap();
        writeln!(out, "    int yy_start_pos;").unwrap();
        writeln!(out, "    int yy_c;").unwrap();
        writeln!(out, "    char yy_save;").unwrap();
        writeln!(out, "    int yy_at_bol_at_start;").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "    if (yyin == NULL) yyin = stdin;").unwrap();
        writeln!(out, "    if (yyout == NULL) yyout = stdout;").unwrap();
        writeln!(out).unwrap();

        // Handle yymore: preserve prior text
        writeln!(out, "    if (yy_more_flag) {{").unwrap();
        writeln!(out, "        yy_more_flag = 0;").unwrap();
        writeln!(out, "        yy_more_len = yyleng;").unwrap();
        writeln!(out, "    }} else {{").unwrap();
        writeln!(out, "        yy_more_len = 0;").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out).unwrap();

        // Main scanner loop
        writeln!(out, "    for (;;) {{").unwrap();

        // Restore held character from previous return
        writeln!(out, "        if (yy_held_pos >= 0) {{ yy_buf[yy_held_pos] = yy_held_char; yy_held_pos = -1; }}").unwrap();
        writeln!(out).unwrap();

        // Buffer refill with proper boundary handling
        writeln!(out, "        /* Refill buffer if needed, preserving partial match data */").unwrap();
        writeln!(out, "        if (yy_buf_pos >= yy_buf_len) {{").unwrap();
        writeln!(out, "            if (yy_refill() == 0) {{").unwrap();
        if !lex_file.options.noyywrap {
            writeln!(out, "                if (yywrap()) return 0;").unwrap();
            writeln!(out, "                continue;").unwrap();
        } else {
            writeln!(out, "                return 0;").unwrap();
        }
        writeln!(out, "            }}").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out).unwrap();

        // DFA simulation (maximal munch)
        writeln!(out, "        yy_at_bol_at_start = yy_at_bol;").unwrap();
        writeln!(out, "        yy_state = YY_START_STATE;").unwrap();
        writeln!(out, "        yy_last_accept_state = -1;").unwrap();
        writeln!(out, "        yy_last_accept_pos = -1;").unwrap();
        writeln!(out, "        yy_start_pos = yy_buf_pos;").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "        while (yy_buf_pos < yy_buf_len) {{").unwrap();
        writeln!(out, "            yy_c = (unsigned char)yy_buf[yy_buf_pos];").unwrap();
        if self.compress {
            writeln!(out, "            yy_state = yy_transition[yy_state][yy_ec[yy_c]];").unwrap();
        } else {
            writeln!(out, "            yy_state = yy_transition[yy_state][yy_c];").unwrap();
        }
        writeln!(out, "            if (yy_state == -1) break;").unwrap();
        writeln!(out, "            yy_buf_pos++;").unwrap();
        writeln!(out, "            if (yy_accept[yy_state] > 0) {{").unwrap();
        writeln!(out, "                yy_last_accept_state = yy_state;").unwrap();
        writeln!(out, "                yy_last_accept_pos = yy_buf_pos;").unwrap();
        writeln!(out, "            }}").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out).unwrap();

        // If we consumed all the buffer, try to refill for longer match
        writeln!(out, "        if (yy_state != -1 && yy_buf_pos >= yy_buf_len) {{").unwrap();
        writeln!(out, "            /* Possible token across buffer boundary — shift and refill */").unwrap();
        writeln!(out, "            if (yy_start_pos > 0) {{").unwrap();
        writeln!(out, "                memmove(yy_buf, yy_buf + yy_start_pos, yy_buf_len - yy_start_pos);").unwrap();
        writeln!(out, "                yy_buf_len -= yy_start_pos;").unwrap();
        writeln!(out, "                yy_buf_pos -= yy_start_pos;").unwrap();
        writeln!(out, "                if (yy_last_accept_pos >= 0)").unwrap();
        writeln!(out, "                    yy_last_accept_pos -= yy_start_pos;").unwrap();
        writeln!(out, "                yy_start_pos = 0;").unwrap();
        writeln!(out, "                int got = (int)fread(yy_buf + yy_buf_len, 1, YY_BUF_SIZE - yy_buf_len, yyin);").unwrap();
        writeln!(out, "                if (got > 0) {{").unwrap();
        writeln!(out, "                    yy_buf_len += got;").unwrap();
        writeln!(out, "                    /* Continue scanning from where we left off */").unwrap();
        writeln!(out, "                    while (yy_buf_pos < yy_buf_len) {{").unwrap();
        writeln!(out, "                        yy_c = (unsigned char)yy_buf[yy_buf_pos];").unwrap();
        if self.compress {
            writeln!(out, "                        yy_state = yy_transition[yy_state][yy_ec[yy_c]];").unwrap();
        } else {
            writeln!(out, "                        yy_state = yy_transition[yy_state][yy_c];").unwrap();
        }
        writeln!(out, "                        if (yy_state == -1) break;").unwrap();
        writeln!(out, "                        yy_buf_pos++;").unwrap();
        writeln!(out, "                        if (yy_accept[yy_state] > 0) {{").unwrap();
        writeln!(out, "                            yy_last_accept_state = yy_state;").unwrap();
        writeln!(out, "                            yy_last_accept_pos = yy_buf_pos;").unwrap();
        writeln!(out, "                        }}").unwrap();
        writeln!(out, "                    }}").unwrap();
        writeln!(out, "                }}").unwrap();
        writeln!(out, "            }}").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out).unwrap();

        // Check if start state is accepting (matches empty string e.g. for a*)
        writeln!(out, "        if (yy_last_accept_state == -1 && yy_accept[YY_START_STATE] > 0) {{").unwrap();
        writeln!(out, "            yy_last_accept_state = YY_START_STATE;").unwrap();
        writeln!(out, "            yy_last_accept_pos = yy_start_pos;").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out).unwrap();

        // Handle match / no match
        writeln!(out, "        if (yy_last_accept_state == -1) {{").unwrap();
        if self.suppress_default {
            // -n flag: discard unmatched char silently
            writeln!(out, "            yy_buf_pos = yy_start_pos + 1;").unwrap();
        } else {
            // Default POSIX behavior: ECHO unmatched char
            writeln!(out, "            yytext = yy_buf + yy_start_pos;").unwrap();
            writeln!(out, "            yyleng = 1;").unwrap();
            writeln!(out, "            ECHO;").unwrap();
            writeln!(out, "            yy_buf_pos = yy_start_pos + 1;").unwrap();
        }
        if lex_file.options.yylineno {
            writeln!(out, "            if (yy_buf[yy_start_pos] == '\\n') yylineno++;").unwrap();
        }
        writeln!(out, "            yy_at_bol = (yy_buf[yy_start_pos] == '\\n');").unwrap();
        writeln!(out, "            continue;").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out).unwrap();

        // Set yytext and yyleng
        writeln!(out, "        yy_buf_pos = yy_last_accept_pos;").unwrap();
        writeln!(out, "        yyleng = yy_buf_pos - yy_start_pos;").unwrap();
        writeln!(out, "        yytext = yy_buf + yy_start_pos;").unwrap();

        if lex_file.options.yylineno {
            writeln!(out, "        {{ int _i; for (_i = 0; _i < yyleng; _i++) {{ if (yytext[_i] == '\\n') yylineno++; }} }}").unwrap();
        }

        // Update BOL flag
        writeln!(out, "        if (yyleng > 0) yy_at_bol = (yytext[yyleng - 1] == '\\n');").unwrap();
        writeln!(out).unwrap();

        // Null-terminate yytext temporarily (hold for restore on next call)
        writeln!(out, "        yy_save = yytext[yyleng];").unwrap();
        writeln!(out, "        yytext[yyleng] = '\\0';").unwrap();
        writeln!(out, "        yy_held_char = yy_save;").unwrap();
        writeln!(out, "        yy_held_pos = (int)(yytext - yy_buf) + yyleng;").unwrap();

        // Switch on accepting rule
        writeln!(out, "        switch (yy_accept[yy_last_accept_state]) {{").unwrap();
        for (i, rule) in lex_file.rules.iter().enumerate() {
            writeln!(out, "            case {}:", i + 1).unwrap();
            let action = rule.action.trim();

            // BOL anchor guard: only match if at beginning of line
            let needs_bol_guard = rule.bol_anchor;
            // EOL anchor guard: only match if at end of line
            let needs_eol_guard = rule.eol_anchor;

            if needs_bol_guard || needs_eol_guard {
                let mut cond = String::new();
                if needs_bol_guard {
                    cond.push_str("yy_at_bol_at_start");
                }
                if needs_eol_guard {
                    if !cond.is_empty() {
                        cond.push_str(" && ");
                    }
                    cond.push_str("(yy_buf_pos >= yy_buf_len || yy_buf[yy_buf_pos] == '\\n')");
                }
                writeln!(out, "                if ({}) {{", cond).unwrap();
            }

            if action.is_empty() {
                if needs_bol_guard || needs_eol_guard {
                    writeln!(out, "                    break;").unwrap();
                } else {
                    writeln!(out, "                break;").unwrap();
                }
            } else {
                let indent = if needs_bol_guard || needs_eol_guard { "                    " } else { "                " };
                writeln!(out, "{}{}", indent, action).unwrap();
                let last_line = action.lines().last().unwrap_or("").trim();
                if !last_line.ends_with("break;")
                    && !last_line.starts_with("return")
                    && !last_line.starts_with("continue")
                {
                    writeln!(out, "{}break;", indent).unwrap();
                }
            }

            if needs_bol_guard || needs_eol_guard {
                // If anchor condition fails, fall through to default echo behavior
                writeln!(out, "                }} else {{").unwrap();
                if !self.suppress_default {
                    writeln!(out, "                    ECHO;").unwrap();
                }
                writeln!(out, "                }}").unwrap();
                writeln!(out, "                break;").unwrap();
            }
        }
        writeln!(out, "            default: break;").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "        yytext[yyleng] = yy_save;").unwrap();
        writeln!(out, "        yy_held_pos = -1;").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        // 7. User code section (copied verbatim)
        if !lex_file.user_code.is_empty() {
            writeln!(out, "/* User code section */").unwrap();
            write!(out, "{}", lex_file.user_code).unwrap();
            writeln!(out).unwrap();
        }

        Ok(out)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::automata::dfa::subset_construction;
    use crate::automata::minimize::minimize_dfa;
    use crate::automata::nfa::NfaBuilder;
    use crate::lex_file::parser::LexFile;

    fn build_output(l_source: &str, suppress_default: bool) -> String {
        let lex_file = LexFile::parse(l_source, "<test>").unwrap();
        let mut builder = NfaBuilder::new();
        let rules: Vec<_> = lex_file
            .rules
            .iter()
            .enumerate()
            .map(|(i, r)| (r.regex.clone(), i))
            .collect();
        let nfa = builder.build_combined(&rules);
        let dfa = subset_construction(&nfa);
        let min_dfa = minimize_dfa(&dfa);

        let emitter = CEmitter::new(suppress_default);
        emitter.emit(&lex_file, &min_dfa).unwrap()
    }

    #[test]
    fn test_emitter_produces_output() {
        let source = "%%\n[0-9]+  printf(\"NUMBER\\n\");\n";
        let output = build_output(source, false);
        assert!(output.contains("#include <stdio.h>"));
        assert!(output.contains("yy_transition"));
        assert!(output.contains("yy_accept"));
        assert!(output.contains("yylex"));
    }

    #[test]
    fn test_emitter_includes_user_actions() {
        let source = "%%\n[0-9]+  printf(\"NUMBER\\n\");\n";
        let output = build_output(source, false);
        assert!(output.contains("printf(\"NUMBER\\n\");"));
    }

    #[test]
    fn test_emitter_header_code() {
        let source = "%{\n#include \"myheader.h\"\n%}\n%%\n.  ;\n";
        let output = build_output(source, false);
        assert!(output.contains("#include \"myheader.h\""));
    }

    #[test]
    fn test_emitter_user_code_section() {
        let source = "%%\n.  ;\n%%\nint main() { return yylex(); }\n";
        let output = build_output(source, false);
        assert!(output.contains("int main() { return yylex(); }"));
    }

    #[test]
    fn test_emitter_noyywrap() {
        let source = "%option noyywrap\n%%\n.  ;\n";
        let output = build_output(source, false);
        assert!(output.contains("static int yywrap"));
        assert!(!output.contains("extern int yywrap"));
    }

    #[test]
    fn test_emitter_yylineno() {
        let source = "%option yylineno\n%%\n.  ;\n";
        let output = build_output(source, false);
        assert!(output.contains("int yylineno = 1;"));
    }

    #[test]
    fn test_emitter_suppress_default() {
        let source = "%%\n[0-9]+  printf(\"NUM\\n\");\n";
        let output = build_output(source, true);
        // With -n, no fputc on unmatched
        assert!(!output.contains("fputc"));
    }

    #[test]
    fn test_emitter_default_echo() {
        let source = "%%\n[0-9]+  printf(\"NUM\\n\");\n";
        let output = build_output(source, false);
        // Without -n, default rule echoes unmatched via ECHO macro
        assert!(output.contains("ECHO"));
    }

    #[test]
    fn test_emitter_dfa_tables_consistent() {
        let source = "%%\na  ;\nb  ;\n";
        let output = build_output(source, false);
        // Should have transition table and accept table
        assert!(output.contains("yy_transition["));
        assert!(output.contains("yy_accept["));
        assert!(output.contains("YY_NUM_STATES"));
        assert!(output.contains("YY_START_STATE"));
    }

    #[test]
    fn test_emitter_empty_action() {
        let source = "%%\n[[:blank:]]  ;\n";
        let output = build_output(source, false);
        // Empty action (;) => just break
        assert!(output.contains("case 1:"));
    }

    // --- Compression tests ---

    fn build_compressed_output(l_source: &str) -> String {
        let lex_file = LexFile::parse(l_source, "<test>").unwrap();
        let mut builder = NfaBuilder::new();
        let rules: Vec<_> = lex_file
            .rules
            .iter()
            .enumerate()
            .map(|(i, r)| (r.regex.clone(), i))
            .collect();
        let nfa = builder.build_combined(&rules);
        let dfa = subset_construction(&nfa);
        let min_dfa = minimize_dfa(&dfa);

        let emitter = CEmitter::with_compression(false);
        emitter.emit(&lex_file, &min_dfa).unwrap()
    }

    #[test]
    fn test_compressed_emitter_has_ec_table() {
        let output = build_compressed_output("%%\n[0-9]+  ;\n");
        assert!(output.contains("yy_ec[256]"));
        assert!(output.contains("yy_ec[yy_c]"));
    }

    #[test]
    fn test_compressed_emitter_smaller_table() {
        let src = "%%\n[0-9]+  ;\n[a-z]+  ;\n";
        let normal = build_output(src, false);
        let compressed = build_compressed_output(src);
        // Compressed output should be shorter (smaller tables)
        assert!(
            compressed.len() < normal.len(),
            "compressed ({}) should be smaller than normal ({})",
            compressed.len(),
            normal.len()
        );
    }

    #[test]
    fn test_compressed_emitter_has_all_sections() {
        let output = build_compressed_output("%%\n.  ;\n");
        assert!(output.contains("#include <stdio.h>"));
        assert!(output.contains("yylex"));
        assert!(output.contains("yy_transition"));
        assert!(output.contains("yy_accept"));
    }
}
