/// Generate the C source code for libl (the lex runtime library).
///
/// libl provides default implementations of:
/// - yywrap() — returns 1 (EOF)
/// - main() — calls yylex() in a loop
pub fn generate_libl_c() -> String {
    r#"/* libl.c — lex runtime library (generated by ft_lex) */
#include <stdio.h>

extern int yylex(void);

int yywrap(void) {
    return 1;
}

int main(void) {
    while (yylex() != 0)
        ;
    return 0;
}
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_libl_contains_yywrap() {
        let src = generate_libl_c();
        assert!(src.contains("int yywrap(void)"));
        assert!(src.contains("return 1;"));
    }

    #[test]
    fn test_libl_contains_main() {
        let src = generate_libl_c();
        assert!(src.contains("int main(void)"));
        assert!(src.contains("yylex()"));
    }

    #[test]
    fn test_libl_includes_stdio() {
        let src = generate_libl_c();
        assert!(src.contains("#include <stdio.h>"));
    }
}
