use std::fmt::Write as FmtWrite;

use crate::automata::arena::NodeId;
use crate::automata::dfa::Dfa;
use crate::compress::equiv_classes::{compress_dfa, CompressedDfa};
use crate::error::LexError;
use crate::lex_file::parser::LexFile;

use super::traits::CodeEmitter;

/// Emits a Rust scanner (lex.yy.rs).
pub struct RustEmitter {
    /// Whether to suppress the default rule (echo unmatched chars).
    pub suppress_default: bool,
    /// Whether to use equivalence-class compression.
    pub compress: bool,
}

impl RustEmitter {
    pub fn new(suppress_default: bool) -> Self {
        Self {
            suppress_default,
            compress: false,
        }
    }

    pub fn with_compression(suppress_default: bool) -> Self {
        Self {
            suppress_default,
            compress: true,
        }
    }

    fn emit_transition_table(out: &mut String, dfa: &Dfa) {
        let n = dfa.state_count();
        writeln!(out, "static YY_TRANSITION: [[i32; 256]; {}] = [", n).unwrap();
        for i in 0..n {
            let state = dfa.arena.get(NodeId(i));
            write!(out, "    [").unwrap();
            for (byte_idx, trans) in state.transitions.iter().enumerate() {
                if byte_idx > 0 {
                    write!(out, ",").unwrap();
                }
                match trans {
                    Some(target) => write!(out, "{}", target.0 as i32).unwrap(),
                    None => write!(out, "-1").unwrap(),
                }
            }
            writeln!(out, "],").unwrap();
        }
        writeln!(out, "];\n").unwrap();
    }

    fn emit_accept_table(out: &mut String, dfa: &Dfa) {
        let n = dfa.state_count();
        write!(out, "static YY_ACCEPT: [i32; {}] = [", n).unwrap();
        for i in 0..n {
            let state = dfa.arena.get(NodeId(i));
            if i > 0 {
                write!(out, ", ").unwrap();
            }
            match state.accepting {
                Some(rule) => write!(out, "{}", rule as i32 + 1).unwrap(),
                None => write!(out, "0").unwrap(),
            }
        }
        writeln!(out, "];\n").unwrap();
    }

    fn emit_ec_table(out: &mut String, cdfa: &CompressedDfa) {
        write!(out, "static YY_EC: [u8; 256] = [").unwrap();
        for i in 0..256 {
            if i > 0 {
                write!(out, ",").unwrap();
            }
            if i % 16 == 0 {
                write!(out, "\n    ").unwrap();
            }
            write!(out, "{}", cdfa.ec.class_of[i]).unwrap();
        }
        writeln!(out, "\n];\n").unwrap();
    }

    fn emit_compressed_transition_table(out: &mut String, cdfa: &CompressedDfa) {
        let nc = cdfa.ec.num_classes;
        writeln!(out, "static YY_TRANSITION: [[i32; {}]; {}] = [", nc, cdfa.num_states).unwrap();
        for s in 0..cdfa.num_states {
            write!(out, "    [").unwrap();
            for c in 0..nc {
                if c > 0 {
                    write!(out, ",").unwrap();
                }
                write!(out, "{}", cdfa.transitions[s * nc + c]).unwrap();
            }
            writeln!(out, "],").unwrap();
        }
        writeln!(out, "];\n").unwrap();
    }

    fn emit_compressed_accept_table(out: &mut String, cdfa: &CompressedDfa) {
        write!(out, "static YY_ACCEPT: [i32; {}] = [", cdfa.num_states).unwrap();
        for i in 0..cdfa.num_states {
            if i > 0 {
                write!(out, ", ").unwrap();
            }
            write!(out, "{}", cdfa.accept[i]).unwrap();
        }
        writeln!(out, "];\n").unwrap();
    }
}

impl CodeEmitter for RustEmitter {
    fn emit(&self, lex_file: &LexFile, dfa: &Dfa) -> Result<String, LexError> {
        let mut out = String::with_capacity(8192);

        // 1. File header
        writeln!(out, "// Generated by ft_lex").unwrap();
        writeln!(out, "use std::io::{{self, Read, Write}};").unwrap();
        writeln!(out).unwrap();

        // 2. User header code
        if !lex_file.header_code.is_empty() {
            writeln!(out, "// User header code").unwrap();
            // Strip C-specific %{{ %}} and #include — user should adapt
            write!(out, "{}", lex_file.header_code).unwrap();
            writeln!(out).unwrap();
        }

        // 3. DFA tables
        let cdfa_opt = if self.compress {
            Some(compress_dfa(dfa))
        } else {
            None
        };

        writeln!(out, "const YY_NUM_STATES: usize = {};", dfa.state_count()).unwrap();
        writeln!(out, "const YY_START_STATE: usize = {};", dfa.start.0).unwrap();
        writeln!(out, "const YY_BUF_SIZE: usize = 16384;").unwrap();
        writeln!(out).unwrap();

        if let Some(ref cdfa) = cdfa_opt {
            Self::emit_ec_table(&mut out, cdfa);
            Self::emit_compressed_transition_table(&mut out, cdfa);
            Self::emit_compressed_accept_table(&mut out, cdfa);
        } else {
            Self::emit_transition_table(&mut out, dfa);
            Self::emit_accept_table(&mut out, dfa);
        }

        // 4. Scanner struct and impl
        writeln!(out, "pub struct Scanner<R: Read> {{").unwrap();
        writeln!(out, "    input: R,").unwrap();
        writeln!(out, "    buf: Vec<u8>,").unwrap();
        writeln!(out, "    pos: usize,").unwrap();
        writeln!(out, "    len: usize,").unwrap();
        if lex_file.options.yylineno {
            writeln!(out, "    pub yylineno: usize,").unwrap();
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "impl<R: Read> Scanner<R> {{").unwrap();
        writeln!(out, "    pub fn new(input: R) -> Self {{").unwrap();
        writeln!(out, "        Scanner {{").unwrap();
        writeln!(out, "            input,").unwrap();
        writeln!(out, "            buf: vec![0u8; YY_BUF_SIZE],").unwrap();
        writeln!(out, "            pos: 0,").unwrap();
        writeln!(out, "            len: 0,").unwrap();
        if lex_file.options.yylineno {
            writeln!(out, "            yylineno: 1,").unwrap();
        }
        writeln!(out, "        }}").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out).unwrap();

        // yylex method
        writeln!(out, "    /// Run the scanner. Returns 0 on EOF.").unwrap();
        writeln!(out, "    pub fn yylex(&mut self) -> i32 {{").unwrap();
        writeln!(out, "        loop {{").unwrap();
        writeln!(out, "            // Refill buffer if needed").unwrap();
        writeln!(out, "            if self.pos >= self.len {{").unwrap();
        writeln!(out, "                match self.input.read(&mut self.buf) {{").unwrap();
        writeln!(out, "                    Ok(0) | Err(_) => return 0,").unwrap();
        writeln!(out, "                    Ok(n) => {{ self.pos = 0; self.len = n; }}").unwrap();
        writeln!(out, "                }}").unwrap();
        writeln!(out, "            }}").unwrap();
        writeln!(out).unwrap();

        // DFA simulation
        writeln!(out, "            let mut state = YY_START_STATE;").unwrap();
        writeln!(out, "            let mut last_accept: i32 = -1;").unwrap();
        writeln!(out, "            let mut last_accept_pos: usize = self.pos;").unwrap();
        writeln!(out, "            let start_pos = self.pos;").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "            while self.pos < self.len {{").unwrap();
        writeln!(out, "                let c = self.buf[self.pos] as usize;").unwrap();
        if self.compress {
            writeln!(out, "                let next = YY_TRANSITION[state][YY_EC[c] as usize];").unwrap();
        } else {
            writeln!(out, "                let next = YY_TRANSITION[state][c];").unwrap();
        }
        writeln!(out, "                if next == -1 {{ break; }}").unwrap();
        writeln!(out, "                state = next as usize;").unwrap();
        writeln!(out, "                self.pos += 1;").unwrap();
        writeln!(out, "                if YY_ACCEPT[state] > 0 {{").unwrap();
        writeln!(out, "                    last_accept = YY_ACCEPT[state];").unwrap();
        writeln!(out, "                    last_accept_pos = self.pos;").unwrap();
        writeln!(out, "                }}").unwrap();
        writeln!(out, "            }}").unwrap();
        writeln!(out).unwrap();

        // Check start state accepting
        writeln!(out, "            if last_accept == -1 && YY_ACCEPT[YY_START_STATE] > 0 {{").unwrap();
        writeln!(out, "                last_accept = YY_ACCEPT[YY_START_STATE];").unwrap();
        writeln!(out, "                last_accept_pos = start_pos;").unwrap();
        writeln!(out, "            }}").unwrap();
        writeln!(out).unwrap();

        // No match
        writeln!(out, "            if last_accept == -1 {{").unwrap();
        if self.suppress_default {
            writeln!(out, "                self.pos = start_pos + 1;").unwrap();
        } else {
            writeln!(out, "                let _ = io::stdout().write_all(&self.buf[start_pos..start_pos+1]);").unwrap();
            writeln!(out, "                self.pos = start_pos + 1;").unwrap();
        }
        if lex_file.options.yylineno {
            writeln!(out, "                if self.buf[start_pos] == b'\\n' {{ self.yylineno += 1; }}").unwrap();
        }
        writeln!(out, "                continue;").unwrap();
        writeln!(out, "            }}").unwrap();
        writeln!(out).unwrap();

        // Match found
        writeln!(out, "            self.pos = last_accept_pos;").unwrap();
        writeln!(out, "            let yytext = &self.buf[start_pos..last_accept_pos];").unwrap();
        writeln!(out, "            let yyleng = yytext.len();").unwrap();
        if lex_file.options.yylineno {
            writeln!(out, "            self.yylineno += yytext.iter().filter(|&&b| b == b'\\n').count();").unwrap();
        }
        writeln!(out, "            let yytext_str = std::str::from_utf8(yytext).unwrap_or(\"\");").unwrap();
        writeln!(out).unwrap();

        // Action switch
        writeln!(out, "            match last_accept {{").unwrap();
        for (i, rule) in lex_file.rules.iter().enumerate() {
            let action = rule.action.trim();
            writeln!(out, "                {} => {{", i + 1).unwrap();
            if action.is_empty() || action == ";" {
                writeln!(out, "                    // discard").unwrap();
            } else {
                // Convert common C patterns to Rust equivalents
                let rust_action = c_action_to_rust(action);
                writeln!(out, "                    {}", rust_action).unwrap();
            }
            writeln!(out, "                }}").unwrap();
        }
        writeln!(out, "                _ => {{}}").unwrap();
        writeln!(out, "            }}").unwrap();

        writeln!(out, "        }}").unwrap(); // end loop
        writeln!(out, "    }}").unwrap(); // end yylex
        writeln!(out, "}}").unwrap(); // end impl
        writeln!(out).unwrap();

        // 5. Default main
        writeln!(out, "fn main() {{").unwrap();
        writeln!(out, "    let stdin = io::stdin();").unwrap();
        writeln!(out, "    let mut scanner = Scanner::new(stdin.lock());").unwrap();
        writeln!(out, "    while scanner.yylex() != 0 {{}}").unwrap();
        writeln!(out, "}}").unwrap();

        // 6. User code section
        if !lex_file.user_code.is_empty() {
            writeln!(out).unwrap();
            writeln!(out, "// User code section").unwrap();
            write!(out, "{}", lex_file.user_code).unwrap();
            writeln!(out).unwrap();
        }

        Ok(out)
    }
}

/// Best-effort conversion of simple C printf/fprintf actions to Rust print! macros.
fn c_action_to_rust(action: &str) -> String {
    let trimmed = action.trim().trim_end_matches(';').trim();

    // printf("...\n", ...) → print!("...\n", ...)
    if let Some(rest) = trimmed.strip_prefix("printf(") {
        if let Some(args) = rest.strip_suffix(')') {
            // Replace %s with {} and %c with {} and %d with {}
            let converted = args
                .replace("%s", "{}")
                .replace("%c", "{}")
                .replace("%d", "{}")
                .replace("%ld", "{}")
                .replace("%f", "{}")
                .replace("yytext", "yytext_str")
                .replace("yyleng", "yyleng")
                .replace("*yytext_str", "yytext_str.chars().next().unwrap_or('?')");
            return format!("print!({});", converted);
        }
    }

    // fprintf(yyout, ...) → eprint!(...)
    if let Some(rest) = trimmed.strip_prefix("fprintf(") {
        if let Some(args) = rest.strip_suffix(')') {
            if let Some(after_stream) = args.strip_prefix("yyout,") {
                let converted = after_stream
                    .trim()
                    .replace("%s", "{}")
                    .replace("%c", "{}")
                    .replace("%d", "{}")
                    .replace("yytext", "yytext_str");
                return format!("print!({});", converted);
            }
        }
    }

    // return X → return X
    if trimmed.starts_with("return") {
        return format!("{};", trimmed);
    }

    // Fallback: wrap in a comment + the original action
    format!("/* C: {} */", action)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::automata::dfa::subset_construction;
    use crate::automata::minimize::minimize_dfa;
    use crate::automata::nfa::NfaBuilder;
    use crate::lex_file::parser::LexFile;

    fn build_rust_output(l_source: &str, compress: bool) -> String {
        let lex_file = LexFile::parse(l_source, "<test>").unwrap();
        let mut builder = NfaBuilder::new();
        let rules: Vec<_> = lex_file
            .rules
            .iter()
            .enumerate()
            .map(|(i, r)| (r.regex.clone(), i))
            .collect();
        let nfa = builder.build_combined(&rules);
        let dfa = subset_construction(&nfa);
        let min_dfa = minimize_dfa(&dfa);

        let emitter = if compress {
            RustEmitter::with_compression(false)
        } else {
            RustEmitter::new(false)
        };
        emitter.emit(&lex_file, &min_dfa).unwrap()
    }

    #[test]
    fn test_rust_emitter_produces_output() {
        let output = build_rust_output("%%\n[0-9]+  printf(\"NUMBER\\n\");\n", false);
        assert!(output.contains("use std::io"));
        assert!(output.contains("YY_TRANSITION"));
        assert!(output.contains("YY_ACCEPT"));
        assert!(output.contains("fn main()"));
        assert!(output.contains("Scanner"));
    }

    #[test]
    fn test_rust_emitter_converts_printf() {
        let output = build_rust_output("%%\n[0-9]+  printf(\"NUM: %s\\n\", yytext);\n", false);
        assert!(output.contains("print!(\"NUM: {}\\n\", yytext_str)"));
    }

    #[test]
    fn test_rust_emitter_has_scanner_struct() {
        let output = build_rust_output("%%\n.  ;\n", false);
        assert!(output.contains("pub struct Scanner<R: Read>"));
        assert!(output.contains("pub fn yylex"));
    }

    #[test]
    fn test_rust_emitter_compressed() {
        let output = build_rust_output("%%\n[0-9]+  ;\n[a-z]+  ;\n", true);
        assert!(output.contains("YY_EC"));
        assert!(output.contains("YY_EC[c]"));
    }

    #[test]
    fn test_rust_emitter_yylineno() {
        let output = build_rust_output("%option yylineno\n%%\n.  ;\n", false);
        assert!(output.contains("yylineno"));
    }

    #[test]
    fn test_rust_emitter_user_code() {
        let output = build_rust_output("%%\n.  ;\n%%\n// custom user code\n", false);
        assert!(output.contains("// custom user code"));
    }

    #[test]
    fn test_c_action_to_rust_printf() {
        assert_eq!(
            c_action_to_rust("printf(\"hello\\n\")"),
            "print!(\"hello\\n\");"
        );
    }

    #[test]
    fn test_c_action_to_rust_return() {
        assert_eq!(c_action_to_rust("return 0"), "return 0;");
    }

    #[test]
    fn test_c_action_to_rust_fallback() {
        assert!(c_action_to_rust("some_random_call()").contains("/* C:"));
    }
}
